### ISSUE TITLE
mujoco actuator

### ISSUE THREAD

**Issue by haewoolee** [google-deepmind/mujoco_menagerie#24]
hi I converted sawyer robot xacro file to urdf using ROS and i loaded in mujoco including mujcoco tag you mentioned. but i was wondering why actuator doesnt seem to work. I heard that we need to use actuator tag to control the joints of robot..
so in other words, i put the actuator tag and loaded in mujoco, and i printed the model bit nu was 0 and there was nothing to control in mujoco gui. is there something else to put to activate actuator in urdf??

**Comment by yuvaltassa** [comment]
URDF does not have the concept of "actuator" like in MuJoCo. You need to add these to the MJCF directly.
