### ISSUE TITLE
Control the franka gripper at the specified speed

### ISSUE THREAD

**Issue by STAY-Melody** [google-deepmind/mujoco_menagerie#27]
Hi!

Is there any way to control the opening and closing speed of the gripper? 

For now, all I know is to adjust the `ctrlrange` of the gripper through `data.ctrl[:]`.

Thanks!

**Comment by kevinzakka** [comment]
You can, just switch the actuator for the gripper to velocity or intvelocity. See the [documentation](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-velocity) for more information.

**Comment by yuvaltassa** [comment]
No, since this changes the dimensionality of the state you have to do in in the XML.

That said, I think  [this feature](https://github.com/google-deepmind/mujoco/issues/1092#issuecomment-1757465249) would solve your problem? (define multiple kinds of actuators, activate/deactivate them at runtime)
