### ISSUE TITLE
Add WidowX

### ISSUE THREAD

**Issue by vyeevani** [google-deepmind/mujoco_menagerie#28]
If you would like to see a new model added to the Menagerie collection, please provide us with the following information _before_ sending a pull request. (Ideally, before you start working on converting or tuning the model for MuJoCo.)

Given recent work from Google like the Open X Embodiment dataset, it would be cool to try policies entirely in simulation. Given my personal workflow is primarily in Brax as opposed to the Gazebo (the native deployment of interbotix), it would be cool to have this integrated.

**URL for the existing model source (e.g. URDF)**
https://github.com/Interbotix/interbotix_ros_manipulators/tree/main/interbotix_ros_xsarms/interbotix_xsarm_descriptions/urdf

**License terms of the upstream model**
BSD 3-Clause License

**What do you think is required to convert and tune this model for MuJoCo?**
You'd have to run the model through argument substitution using ROS's xacro module.

**Are you proposing to help develop and maintain the new model?**
Sure

**Comment by kevinzakka** [comment]
Hey @vyeevani, thanks for your interest in Menagerie. The WidowX and ViperX will be out this week hopefully. Cheers!

**Comment by kevinzakka** [comment]
The ViperX 300 6DOF is now live as of 477ec56566682d663b996d86a188c75499e74b98.

**Comment by ygtkorkmaz** [comment]
Is there any update on WidowX?

**Comment by kevinzakka** [comment]
@ygtkorkmaz Will be out by end of week.
