### ISSUE TITLE
Add the new model of Unitree Go2

### ISSUE THREAD

**Issue by RayYoh** [google-deepmind/mujoco_menagerie#29]
If you would like to see a new model added to the Menagerie collection, please provide us with the following information _before_ sending a pull request. (Ideally, before you start working on converting or tuning the model for MuJoCo.)

**URL for the existing model source (e.g. URDF)**:  [https://github.com/unitreerobotics/unitree_ros/tree/master/robots](Unitree Go2)

**License terms of the upstream model**: BSD 3-Clause License

**What do you think is required to convert and tune this model for MuJoCo?**: Go2 is a new version of Go1 that has been imrpoved.

**Are you proposing to help develop and maintain the new model?**

**Comment by kevinzakka** [comment]
Hey @RayYoh, it will be released within the week.

**Comment by kevinzakka** [comment]
@RayYoh Model is live.
