### ISSUE TITLE
Add UFactory Lite6

### ISSUE THREAD

**Issue by peterdavidfagan** [google-deepmind/mujoco_menagerie#30]
**URL for the existing model source (e.g. URDF)**
[Lite6 URDF](https://github.com/xArm-Developer/xarm_ros2/blob/master/xarm_description/urdf/lite6/lite6.urdf.xacro
)

**License terms of the upstream model**
[BSD 3-Clause](https://github.com/xArm-Developer/xarm_ros2/blob/master/LICENSE
)

**What do you think is required to convert and tune this model for MuJoCo?**
- Being able to convert from the URDF to MuJoCo using the compile command
- Tuning model parameters for actuators

**Are you proposing to help develop and maintain the new model?**
I would be happy to help develop and maintain the new model.

**Comment by kevinzakka** [comment]
Hi @peterdavidfagan, if you can get me the URDF files (not xacro), I can have this out pretty fast.

**Comment by peterdavidfagan** [comment]
Thanks @kevinzakka, I'll clean the URDF  I have (remove ros 2 control tags etc.) and link it here shortly.

**Comment by peterdavidfagan** [comment]
Please find files at the following [link](https://github.com/peterdavidfagan/lite6_urdf_2_mjcf/tree/main/urdf). This loads into the mjviewer so I believe all that is needed is there, if something is missing I'd be happy to add it. Also I haven't included the grippers here but I'd be happy to add these (I am currently working with a custom gripper that someone else open sourced.)


![Screenshot from 2023-11-01 08-35-39](https://github.com/google-deepmind/mujoco_menagerie/assets/42982057/d7fe2d74-dc08-45bf-9e43-ad191568b22a)

**Comment by kevinzakka** [comment]
Hi @peterdavidfagan, did it have any DAE or OBJ files? It would be nice to have pretty visual meshes.

**Comment by kevinzakka** [comment]
If it doesn't exist in the original description, then we can just add textures to the STLs!

**Comment by kevinzakka** [comment]
@peterdavidfagan Model should be released by tomorrow at the latest, cheers :)

**Comment by peterdavidfagan** [comment]
> If it doesn't exist in the original description, then we can just add textures to the STLs!

This is great to know I wasn't aware of this, I have less experience working with 3D modelling (although I have been exploring Blender a bit recently). 

> @peterdavidfagan Model should be released by tomorrow at the latest, cheers :)

This is awesome, thank you so much @kevinzakka.

**Comment by peterdavidfagan** [comment]
Thank you @kevinzakka.
