### ISSUE TITLE
wrong writst pose for Shadow hand

### ISSUE THREAD

**Issue by lianghongzhuo** [google-deepmind/mujoco_menagerie#31]
I guess it is due to the updated mesh?
https://github.com/google-deepmind/mujoco_menagerie/commit/b1874285d2eb986868550f56eb53ec557c420a97

The current wrist mesh's orientation is wrong.

![image](https://github.com/google-deepmind/mujoco_menagerie/assets/16577120/fc580dd5-e750-49b5-9cd0-ac5b83a6bff0)

**Comment by lianghongzhuo** [comment]
This commit is the correct version 32d0026ba3aa440be712aa275cc174c0cb9d79ff

**Comment by kevinzakka** [comment]
Thanks for the bug report, I'll get this fixed asap.

**Comment by kevinzakka** [comment]
This is now fixed, thanks @lianghongzhuo.

**Comment by lianghongzhuo** [comment]
Thank you for the fix!
