### ISSUE TITLE
Documentation regarding joint and actuator parameters on ViperX 300 6DOF

### ISSUE THREAD

**Issue by TyLindberg** [google-deepmind/mujoco_menagerie#38]
When trying to replicate the steps cited to generate [vx300s.xml](https://github.com/google-deepmind/mujoco_menagerie/blob/main/trossen_vx300s/vx300s.xml), I am unable to generate the `kp`, `damping`, `armature`, and `frictionloss` values that are found in the MJCF file in this repo. I was wondering if there were additional steps required to replicate those values, or if they were derived from other sources.

I very well could be missing a step in my conversion from xacro to URDF to MJCF, so I apologize in advance if that is the case.

**Comment by kevinzakka** [comment]
Hi @TyLindberg, those were obtained with a system identification pipeline done by @btaba. We're working on releasing that toolbox soon!
