### ISSUE TITLE
General Question about the reference position of joints

### ISSUE THREAD

**Issue by MegMll** [google-deepmind/mujoco_menagerie#51]
Hi, 

Thank you for the work you're doing to add models to this menagerie. 

I have a question regarding one of attribute in some models. I tried loading the cassie model (`agility_cassie/scene.xml`) in mujoco simulator and realized that some joints position q, when loading the model, were not 0.
And when i checked the model xml (`agility_cassie/cassie.xml`), there is a ref attribute in some of the joints. For instance, the knees : 
`
              <joint name="left-knee" type="hinge" ref="-45" range="-164 -37" damping="1" armature="0.09344"/>
`

I read the documentation about this, and i don't really understand what it represent and why it needs to be added. Could you explain it with a bit more detail, please ?

Thank you in advance or your answer,

**Comment by yuvaltassa** [comment]
Presumably, this related to the values reported by the encoder on the actual robot. These numbers are from Agility, so you're better off asking them 🙂
