### ISSUE TITLE
What metrics are used to evaluate the quality of model?

### ISSUE THREAD

**Issue by zichunxx** [google-deepmind/mujoco_menagerie#52]
Hi!

As the title states, what metrics are used to rate the different models? Or what methods are used to give a score?

Would you mind pointing me in some directions to improve the model quality further?

Thanks!

**Comment by kevinzakka** [comment]
Hi @zichunxx, I've removed the quality grades from the table as of d598afb72e3a520b5127f67803b210415b51c732. Once the system identification toolbox is released (soon!) and models start to get identified, we'll have a more scientific way of scoring the models and I'll update the README accordingly.
