### ISSUE TITLE
how to make the mujoco model

### ISSUE THREAD

**Issue by xsc9202** [google-deepmind/mujoco_menagerie#53]
Hi
I'm a engineer using mujoco to model and simulate,but I want to know how to make the mujoco model?
Now we used the URDF files and mujoco software(mujoco-3.1.3-windows-x86_64\bin\compiel.exe) to convert MJCF format XML files,but has some problem(losing the first body),so can help me ?
thks!
![缺失body](https://github.com/google-deepmind/mujoco_menagerie/assets/167731348/ca939ad8-232a-488a-9e52-b1c3390bddb8)

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/XMLreference.html#compiler-fusestatic
