### ISSUE TITLE
Minimal pick up task using the Franka Panda arm not working as expected

### ISSUE THREAD

**Issue by fahimfss** [google-deepmind/mujoco_menagerie#54]
Hi,

I am trying to create a minimal pick-up a box object simulation using the Franka arm in Python. I have managed to do it using the gymnasium Franka arm [(kitchen_franka)](https://github.com/Farama-Foundation/Gymnasium-Robotics/tree/main/gymnasium_robotics/envs/assets/kitchen_franka). 

Here's my [code](https://github.com/fahimfss/mujoco_tests/blob/main/kitchen_panda/env_test.py) and the [assets](https://github.com/fahimfss/mujoco_tests/tree/main/kitchen_panda).
Here's the output video: 

https://github.com/google-deepmind/mujoco_menagerie/assets/8725869/b4818676-d0cf-4779-8b10-3aeb5cda966b

However, when I tried to do the same thing with the menagerie Franka arm, it could not lift up the box object. 
Here's my [code](https://github.com/fahimfss/mujoco_tests/blob/main/menagerie_panda/env_test.py) and the [assets](https://github.com/fahimfss/mujoco_tests/tree/main/menagerie_panda).
Here's the output:

https://github.com/google-deepmind/mujoco_menagerie/assets/8725869/bfa0541a-006d-4083-aa9b-b2fd25cd4d0f

I saw a few posts with a similar issue ([this](https://github.com/google-deepmind/mujoco/issues/1592), [this](https://github.com/google-deepmind/mujoco/issues/239)). However, I was not able to solve it in my implementation. 

Any help is appreciated. Thank you.

**Comment by yuvaltassa** [comment]
See new section, hope this helps.
https://mujoco.readthedocs.io/en/latest/modeling.html#preventing-slip

**Comment by fahimfss** [comment]
Thank you @yuvaltassa. It turned out that the fingers of Franka's arm were not applying enough force. Updating this line: 

```
<general class="panda" name="actuator8" tendon="split" forcerange="-100 100" ctrlrange="0 255"
      gainprm="0.01568627451 0 0" biasprm="0 -100 -10"/>
```

to this: 

```
<general class="panda" name="actuator8" tendon="split" forcerange="-100 100" ctrlrange="0 255" gear="20 0 0 0 0 0"
      gainprm="0.3137254902 0 0" biasprm="0 -100 -10"/>
```

in the [panda.xml](https://github.com/google-deepmind/mujoco_menagerie/blob/main/franka_emika_panda/panda.xml) file mostly solved the issue for me. Added `<option  impratio="10" noslip_iterations="3"/>` to slow down slipping.
