### ISSUE TITLE
MJX model versions

### ISSUE THREAD

**Issue by peterdavidfagan** [google-deepmind/mujoco_menagerie#58]
**Which model is the issue affecting?**

All model releases (in particular those models containing features that are supported in `mujoco` but not `mujoco-mjx`).

**What is the issue?**

It would be nice if model releases include mjx compatible versions. Models that contain tendons for instance are not supported in mjx, right now users have to alter published models containing tendons to use them with mjx, it would be nice if there was official support for mjx compatible models. 

**Is there any additional context you can provide (e.g., a spec sheet or a URDF to show a value mismatch)?**

I have been trying to use the [robotiq_2f85](https://github.com/google-deepmind/mujoco_menagerie/tree/main/robotiq_2f85) model with mjx but I have encountered the following error:

```
 File "/home/peter/.cache/pypoetry/virtualenvs/mujoco-robot-environments-hs2qeFWj-py3.10/lib/python3.10/site-packages/mujoco/mjx/_src/io.py", line 69, in put_model
    raise NotImplementedError('tendons are not supported')
NotImplementedError: tendons are not supported
```

Update: my bad I see that tendons will be supported in future, maybe the main thing is to wait for feature parity. Although there are other important considerations like the integrator and collision geometries for which it may be worth supporting another file for mjx.

**Comment by kevinzakka** [comment]
Hi @peterdavidfagan, we do have MJX-compatible models for certain robots, e.g. see anymal C, Unitree Go2 and Google Barkour robots. Not all models are simulate-able in MJX due to lack of feature parity, but having an MJX-version for all robots that support it is on our roadmap and we are actively accepting community contributions! I'll add an MJX column to the README table to make this more visible.

**Comment by peterdavidfagan** [comment]
Ah ok understood, thanks @kevinzakka for clarifying this.

**Comment by kevinzakka** [comment]
@peterdavidfagan I just pushed a commit that improves the README. There should now be an MJX column in the main table telling you if an MJX-compatible model is available. Cheers!

**Comment by peterdavidfagan** [comment]
Thanks @kevinzakka.
