### ISSUE TITLE
unitree_g1 issue

### ISSUE THREAD

**Issue by chauncygu** [google-deepmind/mujoco_menagerie#63]
**Which model is the issue affecting?**
unitree_g1
**What is the issue?**
When I run 
`python -m mujoco.viewer --mjcf mujoco_menagerie/unitree_g1/scene.xml`
this happens:
XML Error: Schema violation: unrecognized attribute: 'ellipsoidinertia'
Element 'global', line 0

**Is there any additional context you can provide (e.g., a spec sheet or a URDF to show a value mismatch)?**
Run on a Ubuntu 20.04 system, with Python 3.10

**Comment by kevinzakka** [comment]
Hi @chauncygu,

Looks like the minimum required version on the G1 is incorrect, it should be 2.3.4. You can either remove the `ellipsoidinertia` attribute (it won't affect the model in any way) or upgrade your MuJoCo version to at least 2.3.4 (I would recommend the latest).
