### ISSUE TITLE
Collision Issue in `spot_arm.xml` Model's `arm_link_sh0` Link

### ISSUE THREAD

**Issue by jc-bao** [google-deepmind/mujoco_menagerie#73]
**Which model is the issue affecting?**

`spot_arm.xml`

**What is the issue?**

The model's link `arm_link_sh0` has a collision with other links. 

**Is there any additional context you can provide (e.g., a spec sheet or a URDF to show a value mismatch)?**

Here is the contact force: 

<img width="542" alt="image" src="https://github.com/user-attachments/assets/207e8ecf-0bf1-48d5-bd0a-b347df620248">

As you can see, the arm base has a large contact force, making the arm immovable. By removing the following collision geometries:

```xml
<geom class="collision" mesh="arm_link_sh0_base_coll" />
<geom class="collision" mesh="arm_link_sh0_left_motor_coll" />
<geom class="collision" mesh="arm_link_sh0_right_motor_coll" />
```

The arm can move freely.

**Comment by kevinzakka** [comment]
@jc-bao I cannot reproduce this locally. We [carefully checked and excluded](https://github.com/google-deepmind/mujoco_menagerie/blob/main/boston_dynamics_spot/spot_arm.xml#L253-L258) spurious collisions.

What MuJoCo version are you using?

**Comment by jc-bao** [comment]
Hi @kevinzakka, I am using `3.1.6` under Ubuntu 22.04. Let me double check the original model and see what's wrong. My modification is to fix the base and only test the `diffik` in your repo. Thanks for the prompt response!

**Comment by kevinzakka** [comment]
@jc-bao By "fix base", do you mean removing the `freejoint`? If the answer is yes, then that explains the behavior you are seeing. The reason is that MuJoCo excludes collisions between parent and child bodies by default, but this exclusion is not applied if the parent is a static body (aka world or dof-less descendant of world).

**Comment by kevinzakka** [comment]
To fix your issue, you can add `<exclude body1="body" body2="arm_link_sh0"/>` to the exclude clause of the XML.

**Comment by jc-bao** [comment]
Oh that make sense. I can confirm that the original model works fine. After exclude the contact, it works perfectly. Thanks!

**Comment by yuvaltassa** [comment]
For future reference, this is documented here

https://mujoco.readthedocs.io/en/3.2.0/overview.html#surprising-collisions
