### ISSUE TITLE
LEAP HAND SUPPORT

### ISSUE THREAD

**Issue by kingchou007** [google-deepmind/mujoco_menagerie#84]
Hi,

Do you have any plans to officially support Leap Hand XML?

**URL for the existing model source (e.g. URDF)**
https://leaphand.com/

**Comment by kevinzakka** [comment]
Will get the leap hand in sometime in the next 2 weeks!

**Comment by Lucky7Chess** [comment]
Let me know if you need help with that! @kevinzakka

**Comment by kevinzakka** [comment]
Hi folks, LEAP hand PR [is live](https://github.com/google-deepmind/mujoco_menagerie/pull/91).

@Lucky7Chess Could I get a high level review from you to make sure things look good? Cheers!
