### ISSUE TITLE
Model keeps contacting and jump around

### ISSUE THREAD

**Issue by leeygang** [google-deepmind/mujoco_menagerie#87]
I am trying to learn how to build the convex hull geom model learning from op3. After I add convex hull stl mesh geom, the robot keeps jumping around. there is consistent contacting force showing between the 2 new convex hull mesh(the ankle and the lower leg), there is no such problem in op3 model. Is there anything wrong in my setup? Thanks in advanced. 
I attached the model and the recorded video. 
here is the xml file of my model: https://github.com/leeygang/robot/blob/main/gym/mujoco/robot.xml
The conflict is between ankle and lower leg(left_ankle.stl, left_lower_leg.stl) under https://github.com/leeygang/robot/tree/main/gym/mujoco/assets/convex

convex mesh:
![Screenshot 2024-08-11 114812](https://github.com/user-attachments/assets/6c2fc92d-6f7a-4850-be20-b8073be085e4)
![Screenshot 2024-08-11 114820](https://github.com/user-attachments/assets/561033f9-10cf-4a6e-941d-b72431e52ee2)

recorded mujoco viewer:
https://github.com/user-attachments/assets/e26c4ea3-7e79-461b-8a7b-afdb6e93d7e8

**Comment by kevinzakka** [comment]
https://mujoco.readthedocs.io/en/latest/XMLreference.html#contact-exclude

https://github.com/google-deepmind/mujoco_menagerie/blob/main/robotis_op3/op3.xml#L236
