### ISSUE TITLE
adding grippers to models

### ISSUE THREAD

**Issue by mehdikhfifi** [google-deepmind/mujoco_menagerie#90]
**Which model is the issue affecting?**
ur5e
**What is the issue?**
Is it possible to add grippers to some of the models, like say the ur5e, and if so, what would the steps be

**Is there any additional context you can provide (e.g., a spec sheet or a URDF to show a value mismatch)?**

**Comment by kevinzakka** [comment]
You can use the new official [MjSpec API](https://mujoco.readthedocs.io/en/stable/programming/modeledit.html) or use [MJCF](https://github.com/google-deepmind/dm_control/blob/main/dm_control/mjcf/README.md) from dm_control, in which case this [FAQ](https://github.com/google-deepmind/mujoco_menagerie/blob/main/FAQ.md) may be helpful.
